config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "accounts"
  resources :shopping_items, except: %i(index) do
    get 'delete', on: :member
    get 'toggle_active', on: :member
  end
  get '/shopping_list', to: 'shopping_items#index'
    
  resources :recipes

  root 'recipes#index'
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  picture    :string
#  user_id    :integer
#  component  :boolean          default("false")
#
class Recipe < ActiveRecord::Base
  include WithPicture
  has_default_picture_size [400, 400]
  has_thumb_picture_size [50, 50]

  DEPENDENT_ATTRIBUTES = {
    ingredients: :value,
    steps: :description,
    references: :url,
    recipe_components: :component_id
  }

  validates :name, uniqueness: true, presence: true

  belongs_to :user

  DEPENDENT_ATTRIBUTES.each do |dependent, attr|
    has_many dependent, dependent: :destroy
    accepts_nested_attributes_for dependent,
                                  allow_destroy: true,
                                  reject_if: -> (params) { params[attr].blank? }
  end

  has_many :components, through: :recipe_components, class_name: 'Recipe'
  accepts_nested_attributes_for :components, allow_destroy: true

  scope :component, -> { where(component: true) }

  def user_name
    user ? user.name : 'N/A'
  end

  def prepare_recipe(params)
    self.name = params[:name].try(:strip)
    self.user_id = params[:user_id]
    self.component = params[:component]
    build_dependents(params)

    self
  end

  # builds ingredients, steps and references if specified in params
  # hash
  def build_dependents(params)
    DEPENDENT_ATTRIBUTES.each do |dependent, attr|
      next if params[dependent].blank?
      params[dependent].split("\n").map(&:strip).each do |str|
        next if str.blank?
        # e.g. ingredients.build(value: 'something ingredient')
        (send dependent).build(attr => str)
      end
    end
  end
end

app/controllers/recipes_controller.rb
#
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    respond_to do |format|
      format.html {}
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  def new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = new_recipe

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        @render_final_form = true
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.includes(:ingredients, :references, :components).find(params[:id])
  end

  def new_recipe
    if new_params.empty?
      # after re-display of new, with final form
      Recipe.new(recipe_params)
    else
      Recipe.new.prepare_recipe(new_params)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(
      :name,
      :user_id,
      :component,
      :picture,
      :remove_picture,
      :picture_cache,
      ingredients_attributes: [:id, :value, :_destroy],
      steps_attributes: [:id, :description, :picture, :remove_picture, :picture_cache, :_destroy],
      references_attributes: [:id, :url, :_destroy], component_ids: []
    )
  end

  def new_params
    params.permit(:name, :user_id, :component, :ingredients, :steps, :references)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def allow_edit?(recipe)
    return false unless user_signed_in?
    recipe.user_id == current_user.id
  end
end

app/views/recipes/_add_nested_field.html.haml
= form.link_to_add target do
  %span.btn.btn-default
    = tooltip

app/views/recipes/_component.html.haml
.panel.panel-basic
  .panel-heading{ id: "heading#{recipe.id}", role: 'tab' }
    %h4.panel-title
      = link_to recipe.name, "#collapse#{recipe.id}", class: 'collapsed', data: { toggle: 'collapse', parent: '#components' }, :'aria-expanded' => 'false', :'aria-controls' => "collapse#{recipe.id}"
  .panel-collapse.collapse{ id: "collapse#{recipe.id}", role: 'tabpanel', aria: { labeledby: "heading#{recipe.id}" } }
    .panel-body
      .row
        .col-md-4.col-md-push-8
          %h4 Ingredients
          %ul.list-unstyled.ingredients
            - recipe.ingredients.each do |ingredient|
              %li= ingredient.value
        .col-md-8.col-md-pull-4
          .recipe-directions        
            - recipe.steps.each do |step|
              %p= step.description

          .recipe-link
            = link_to recipe_path(recipe), title: recipe.name, data: { toggle: 'tooltip' } do
              = glyph :'chevron-right'
              Go to Recipe

app/views/recipes/_form.html.haml
= simple_nested_form_for @recipe do |f|
  = f.input :user_id, as: :hidden, input_html: { value: current_user_id }
  = f.input :name, label: false
  = f.input :component, as: :boolean, label: false, inline_label: 'Component Recipe', input_html: { class: 'checkbox checkbox-inline' }
  
  %h2 Picture
  = render partial: 'picture', locals: { form: f }

  %h2 Components
  = f.association :components, collection: Recipe.component.all, label: false

  %h2 Ingredients
  #ingredients
    = f.fields_for :ingredients, :wrapper => false do |i_form|
      .row.form-group
        .col-md-11
          = i_form.input :value, label: false
        .col-md-1
          = render partial: 'remove_nested_field', locals: { form: i_form, tooltip: 'Remove this Ingredient' }  
    = render partial: 'add_nested_field', locals: { form: f, tooltip: 'Add an Ingredient', target: :ingredients }
        
  %h2 Directions
  #steps
    = f.fields_for :steps do |d_form|
      = render partial: 'picture', locals: { form: d_form }
      .row.form-group
        .col-md-11
          = d_form.input :description, label: false, input_html: { class: 'autoExpand' }
        .col-md-1
          = render partial: 'remove_nested_field', locals: { form: d_form, tooltip: 'Remove this Step' }  
    = render partial: 'add_nested_field', locals: { form: f, tooltip: 'Add a Step', target: :steps }
        
  %h2 References
  #references
    = f.fields_for :references do |r_form|
      .row.form-group
        .col-md-11
          = r_form.input :url, input_html: { placeholder: "Enter URL" }, label: false
        .col-md-1
          = render partial: 'remove_nested_field', locals: { form: r_form, tooltip: 'Remove this Reference' }
    = render partial: 'add_nested_field', locals: { form: f, tooltip: 'Add a Reference', target: :references }

  %br
    
  = f.button :submit, 'Update', title: 'Update this Recipe', data: { toggle: 'tooltip' }, class: 'btn btn-default'

app/views/recipes/_picture.html.haml
.row.form-group
  .col-md-12
    .input-group.input-group
      .input-group-addon
        = glyph :picture
      = form.input :picture, label: false, input_html: { title: form.object.picture_file_name || 'No Picture Selected Yet' }
- if form.object.picture?
  = form.input :picture_cache, as: :hidden
  - label_text = "Remove Current Picture"
  = form.input :remove_picture, as: :boolean, label: false, inline_label: label_text, input_html: { class: 'checkbox checkbox-inline' }
  %br

app/views/recipes/_pre_form.html.haml
= form_tag recipes_path, method: :post, html: { class: 'form-horizontal' } do |f|
  = hidden_field_tag :user_id, current_user_id
  = text_field_tag 'name'

  %br
  = check_box_tag 'component'
  = label_tag 'Component Recipe'
  
  %h2 Ingredients
  = text_area_tag 'ingredients', nil, class: 'form-control', rows: 10

  %h2 Directions
  = text_area_tag 'steps', nil, class: 'form-control', rows: 10

  %h2 References
  = text_area_tag 'references', nil, class: 'form-control', rows: 2

  %br
  = submit_tag 'Submit'

app/views/recipes/_remove_nested_field.html.haml
= form.link_to_remove title: tooltip, data: { toggle: 'tooltip' } do
  %span.btn.btn-default
    = glyph :trash

app/views/recipes/edit.html.haml
- model_class = Recipe
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/recipes/index.html.haml
- model_class = Recipe
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table
  %thead
    %tr
      %th
      %th= model_class.human_attribute_name(:name)
      %th.hidden-xs= model_class.human_attribute_name(:user)
      %th.hidden-xs= model_class.human_attribute_name(:created_at)
      %th.hidden-xs
  %tbody
    - @recipes.each do |recipe|
      %tr
        %td
          - if recipe.picture?
            = link_to image_tag(recipe.picture_url :thumb), recipe_path(recipe)
        %td= link_to recipe.name, recipe_path(recipe)
        %td.hidden-xs= recipe.user_name
        %td.hidden-xs= local_time(l recipe.created_at, format: :long)
        %td.hidden-xs
          .btn-group
            .btn.btn-sm
              = render partial: 'layouts/edit_btn', locals: { path: edit_recipe_path(recipe), disabled: !(allow_edit? recipe) }
            .btn.btn-sm
              = render partial: 'layouts/delete_btn', locals: { path: recipe_path(recipe), disabled: !(allow_edit? recipe)  }

= link_to new_icon, new_recipe_path, title: 'Add a New Recipe', data: { toggle: 'tooltip' }

app/views/recipes/new.html.haml
- model_class = Recipe

.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize

  - if @render_final_form
    = render :partial => 'form'
  - else
    = render :partial => 'pre_form'

app/views/recipes/show.html.haml
- model_class = Recipe
.page-header
  .row.text-center
    = image_tag(@recipe.picture_url) if @recipe.picture?

  %h1=t '.title', :default => title || model_class.model_name.human.titleize

  .recipe-user
    = glyph :user
    = @recipe.user_name
    = glyph :calendar
    = l @recipe.created_at.to_date, format: :short

#components.panel-group{ role: 'tablist', aria: { multiselectable: 'true' } }
  - @recipe.components.each do |recipe|
    = render partial: 'component', locals: { recipe: recipe }
    
.row
  .col-md-4.col-md-push-8
    %h4 Ingredients
    %ul.list-unstyled.ingredients
      - @recipe.ingredients.each do |ingredient|
        %li= ingredient.value
  .col-md-8.col-md-pull-4
    .recipe-directions        
      - @recipe.steps.each do |step|
        %p
          = image_tag(step.picture_url) if step.picture?
          = step.description

    - if @recipe.references.any?      
      %h4 References
      %ul.list-unstyled.references
        - @recipe.references.each do |reference|
          %li= link_to reference.url, reference.url.html_safe

    - if allow_edit? @recipe
      .btn-group
        .btn.btn-default
          = render partial: 'layouts/edit_btn', locals: { path: edit_recipe_path(@recipe) }
        .btn.btn-default
          = render partial: 'layouts/delete_btn', locals: { path: recipe_path(@recipe) }