config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "accounts"
  resources :shopping_items, except: %i(index) do
    get 'delete', on: :member
    get 'toggle_active', on: :member
  end
  get '/shopping_list', to: 'shopping_items#index'
    
  resources :recipes

  root 'recipes#index'
end

app/models/shopping_item.rb
# == Schema Information
#
# Table name: shopping_items
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  active     :boolean          default("true")
#
class ShoppingItem < ActiveRecord::Base
  belongs_to :user
end

app/controllers/shopping_items_controller.rb
class ShoppingItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_item, except: %i(index new create)
  before_action :set_items, only:  %i(index)

  respond_to :html, :js

  def index
  end

  def show
    respond_to_js
  end

  def new
    @item = @user.shopping_items.new
  end

  # we don't want to create the same item more than once.  if we
  # already have this item, we rather want to set it to active
  def create
    respond_to_js do
      @item = @user.shopping_items.find_by(name: shopping_item_params[:name])
      if @item
        @item.update(active: true)
      else
        @item = @user.shopping_items.create(shopping_item_params)
      end
      set_items
    end
  end

  def edit
    respond_to_js
  end

  def update
    @item.update_attributes(shopping_item_params)
    set_items
  end

  def delete
    respond_to_js
  end

  def destroy
    respond_to_js do
      @item.destroy
      set_items
    end
  end

  def toggle_active
    respond_to_js do
      @item.toggle :active
      @item.save
      set_items
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_item
    @item = ShoppingItem.find(params[:id])
  end

  # sorting: list active items first
  def set_items
    @items = @user.shopping_items(true).sort_by { |item| item.active ? 0 : 1 }
  end

  def shopping_item_params
    params.require(:shopping_item).permit(:name, :active, :id)
  end

  def respond_to_js
    respond_to do |f|
      yield if block_given?
      f.html { render nothing: true }
      f.js
    end
  end
end

app/helpers/shopping_items_helper.rb
module ShoppingItemsHelper
end

app/views/shopping_items/_delete.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h3 Delete Item
    .modal-body
      %ul.errors
      Are you sure you wish to delete
      %strong
        = @item.name
      = '?'
    .modal-footer
      .btn-group
        .btn.btn-sm
          = link_to 'Yes, Delete This Item', shopping_item_path(@item), method: :delete, remote: true
        .btn.btn-sm
          = link_to 'No, Keep It', '#', data: { dismiss: 'modal' }

app/views/shopping_items/_edit.html.haml
.modal-header
  %h3= "Editing #{@item.name}"
= render 'form'

app/views/shopping_items/_form.html.haml
.modal-dialog
  .modal-content
    = simple_form_for @item, remote: true do |f|
      .modal-body
        %ul.errors

        = f.input :name
      .modal-footer    
        = f.button :submit, 'Update'
        = link_to 'Cancel', '#', data: { dismiss: 'modal' }

        

app/views/shopping_items/_index.html.haml
- if @items.empty?
  .alert.alert-info
    Your shopping list is empty...
- else
  .list-group
    - @items.each do |item|
      .row
        .col-md-11.col-xs-11
          - cl = "list-group-item"
          - cl = "#{cl} disabled" unless item.active
          = link_to toggle_active_shopping_item_path(item), remote: true, class: cl do
            = item.name
        .col-md-1.col-xs-1
          - ["visible-xs btn-group-xs", "hidden-xs btn-group-default"].each do |cl|
            .btn-group.btn-group-justified{ class: cl }
              .btn
                = render partial: 'layouts/edit_btn', locals: { path: edit_shopping_item_path(item), remote: true }
              .btn
                = link_to delete_shopping_item_path(item), :data => { toggle: 'tooltip' }, title: t('.destroy', :default => t("helpers.links.destroy")), remote: true do
                  = glyph :trash
      

app/views/shopping_items/_new.html.haml
.modal-header
  %h3 New Item
= render 'form'

app/views/shopping_items/_save.js.erb
$("ul.errors").html("")
<% if @item.errors.any? %>
   <% @item.errors.full_messages.each do |message| %>
      $("ul.errors").append("<li />").html("<%= message.html_safe %>")
   <% end %>
<% else %>
   $("#item-list").html("<%= escape_javascript(render 'index') %>")
   $("#item-modal").modal("hide")
<% end %>

app/views/shopping_items/create.js.erb
<%= render "save" %>

app/views/shopping_items/delete.js.erb
$("#item-modal").html("<%= escape_javascript(render 'delete') %>")
$("#item-modal").modal("show")

app/views/shopping_items/destroy.js.erb
<%= render 'save' %>

app/views/shopping_items/edit.js.erb
$("#item-modal").html("<%= escape_javascript(render 'edit') %>")
$("#item-modal").modal("show")

app/views/shopping_items/index.html.haml
%h1 Shopping List

#item-list
  = render 'index'

#item-modal.modal.fade
  
= link_to new_icon, new_shopping_item_path, remote: true, data: { toggle: :modal, target: '#item-modal' }

app/views/shopping_items/new.js.erb
$("#item-modal").html("<%= escape_javascript(render 'new') %>")
$("#item-modal").modal("show")

app/views/shopping_items/toggle_active.js.erb
$("#item-list").html("<%= escape_javascript(render 'index') %>")

app/views/shopping_items/update.js.erb
<%= render "save" %>