config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "accounts"
  resources :shopping_items, except: %i(index) do
    get 'delete', on: :member
    get 'toggle_active', on: :member
  end
  get '/shopping_list', to: 'shopping_items#index'
    
  resources :recipes

  root 'recipes#index'
end

app/views/layouts/_delete_btn.html.haml
- remote ||= false
- if disabled ||= false
  = link_to '#', data: { toggle: 'tooltip' }, title: 'Nope...', disabled: true do
    = glyph :trash
- else
  = link_to path, method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')), toggle: 'tooltip' }, title: t('.destroy', default: t("helpers.links.destroy")), remote: remote do
    = glyph :trash

app/views/layouts/_edit_btn.html.haml
- remote ||= false
- if disabled ||= false
  = link_to '#', disabled: true do
    = glyph :pencil
- else
  = link_to path, title: t('.edit', default: t("helpers.links.edit")), data: { toggle: 'tooltip' }, remote: remote do
    = glyph :pencil

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Cookie"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = javascript_include_tag "application"

  %body
    #content.container-fluid
      .menu
        .login-menu
          - if user_signed_in?
            = link_to image_tag('notepad-icon.png', alt: 'Logout'), shopping_list_path, title: 'Shopping List', data: { toggle: 'tooltip' }
            = link_to image_tag('logout-icon.png', alt: 'Logout'), destroy_user_session_path, :method => :delete, title: 'Logout', data: { toggle: 'tooltip' }
            = current_user.name
          - else
            = link_to image_tag('login-icon.png', alt: 'Login'), new_user_session_path, title: "You're not logged in yet...", data: { toggle: 'tooltip' }
        .main-menu
          = link_to image_tag('home-icon.png'), recipes_path, title: 'Recipe Overview', data: { toggle: 'tooltip' }
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
  %footer